# golangci-lint configuration for Termite
# See https://golangci-lint.run/usage/configuration/
version: "2"

linters:
  enable:
    - gosec         # Security issues
    - govet         # Standard Go vet checks
    - ineffassign   # Detect unused assignments
    - misspell      # Spelling mistakes
    - staticcheck   # Comprehensive static analysis
    - unused        # Unused code detection
  settings:
    gosec:
      excludes:
        # G115: Integer overflow conversion - these are safe in practice:
        # - Array lengths won't exceed uint32 max
        # - Pool indices use modulo operation which bounds the result
        # - Config values are validated at load time
        - G115
        # G301: Directory permissions 0755 - model directories need to be readable
        # for users to access downloaded model files
        - G301
        # G304: File inclusion via variable - expected for model registry operations
        # The model registry legitimately reads model files from user-specified paths
        - G304
        # G306: WriteFile permissions 0644 - model files should be readable by others
        - G306

formatters:
  enable:
    - gofmt      # Standard Go formatting
    - goimports  # Manage imports and format

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  fix: true

run:
  timeout: 5m
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 4

severity:
  default: error
