// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// ChunkerModelsDir Directory containing chunker ONNX models. Termite will discover and load all models in this directory (similar to Ollama). If not set, only built-in 'fixed' chunking is available.
	ChunkerModelsDir string                             `json:"chunker_models_dir,omitempty,omitzero"`
	ContentSecurity  externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// EmbedderModelsDir Directory containing embedder ONNX models. Termite will discover and load all models in this directory (similar to Ollama). If not set, embedding endpoint will not be available.
	EmbedderModelsDir string `json:"embedder_models_dir,omitempty,omitzero"`

	// Gpu GPU acceleration mode:
	// - "auto": Auto-detect GPU availability (default). Uses CUDA on Linux if nvidia-smi is available, CoreML on macOS.
	// - "true": Force GPU on. Will fail at runtime if GPU is not available.
	// - "false": Force GPU off (CPU only).
	//
	// On macOS, CoreML is always used when available (no configuration needed).
	// On Linux, CUDA is auto-detected via nvidia-smi or CUDA library presence.
	// Legacy env var ANTFLY_USE_CUDA=1 still works but this config takes precedence.
	Gpu string `json:"gpu,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in embedder_models_dir (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string `json:"request_timeout,omitempty,omitzero"`

	// RerankerModelsDir Directory containing reranker ONNX models. Termite will discover and load all models in this directory (similar to Ollama). If not set, reranking endpoint will not be available.
	RerankerModelsDir string                   `json:"reranker_models_dir,omitempty,omitzero"`
	S3Credentials     externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from embedder_models_dir
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from embedder_models_dir
	Embedders []string `json:"embedders"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from `reranker_models_dir`
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8e3PbOPLgV0Fxrir2HPWwnWQSXc0fHk8yP9/PeaztbG5vlJIhsiVhDAIMAMpWUv7u",
	"V90AXyJlOzubuf1jq1IViwQajUa/u8GvUaKzXCtQzkaTr5FNVpBx+vNkVahr/CMFmxiRO6FVNImOWYIv",
	"mF4wB7eO3Qi3Yrm2At8zoRbaZBz/HkZxlBudg3ECCCKodJasuOkCPVlxwxMHpgmJaSOWQnEZFlqBgbA4",
	"qNSyPbhNZGHFGvajOHKbHKJJJJSDJZjoLo5E2l3oAj4XoBJgqsjmYGgXqxLq3jhmBzE7jNlwOOyBGUe3",
	"g6UehKeFUO7oEBeyjhv3L9oZwbK9+8Gx3QUuK/QTrRwoV8+1zgi1jO7u4sjA50IYSKPJ70iXAKyFelyf",
	"z6cKhJ7/AYnD1YkdTrRaiGXPLul5Yejg2UIbj5JQS4Yrg3WWOc0uwWTCATt+fzqcqsuVsExYxpkVWS7F",
	"QkCKm1iIJYHAg/mvy8v3OJwNWCoWCzCWLYzO6N2ikJIRWmA8AlN1sxLJigmVyCIFy3Kj1yIFwyxISAg5",
	"rlKW8GSFuCVNtIdT1eHYjN/OaCfW73nBC+miybNxvEWAN/xWZEXWYCs/DXdtwBUGYcMtz3IJfn73fDOd",
	"gmytEy3ELeBp7Thy3APNwmUKC0P2SrgVGPaEJj4hMhJxgTl9DWow5xaJHCbHTBvGAwjFM/DEpd92lHjS",
	"2tFXfHU3Gja3UKG2xWtxpNdgJM9ntOBDdHtb0StMy3FPfiqbg7sBUIGUDxPQQs4Nd9q0iThVdLJbNETB",
	"qyYQoWhHFW1amw0gOnt13CzB9W+1s9dLGtzUPH6bOQRxae+wd4tuZcCutExbi42Hz+I+iUxJ1VVzaJfv",
	"3r79P+GE2d54OB4cDMf7zZUJmNfieMxS84ZK8ciTSunXEOde3BG9tigller4HwYW0ST6YVSbnlGwO6Om",
	"ltmt8vDsnO4SLapVitRqyVKdFBkox9yKO6YAUhLIOTCbS+GYUE4zm3EpyyOww+HwQQVKWH3aTQGba2WB",
	"LF6J2dcIdQ7MVsJFkwWXFuKoVCy/e8uoFwsLLpoc4Mln4HjKHY8mXysDUw4Yl3SptkvaUBjr/CZwD3fx",
	"FtSXD0B92Q/WQqJV2oD7qVJUQQXcbSvNxk63T+7jCkg/GbCFdOyGW2bBrCH1iodm1uSfay2BK1yhqYRb",
	"3ogxfFP5IpWiEA4y+yhei2pO5ghrSxG3TXlL5fLEFVzKDSrelO1lfBNMlN9LsHuQMrFgCy7lnCfXTCdJ",
	"YQyk+4/RpVtsV+3O4xc3CN3LjJXAtY+H52JWmJ79fTg/K/2h0lBDNoc0FWo5quwNnpdIoIX/yrl8MhpJ",
	"nXC50tZNXoxfjKOGFimM6FOfwcLMvDqapWJLcw9HW6aoo8Z/FQYSp82GvB8uFJl1P7qp6obVlm6ElCwV",
	"NkGDQ96A1DxlXMpSKwrFHEpAWsHesyITkhtUHu+k5BnfH7LTBVMabYiLmVZyw+aFkG4gVGV9K5qhRlpz",
	"IflcQtuK9u2wSybv2M0sJIURbvMQY3PlFnIzWOqZFHO+mNnEcLSrM52DwuM/8QAvArxa3/rzfsyJlCMf",
	"eSTl8L/wTCrexWgh10I5vw4OmMODB9LcYOdElnnRpgsvnO5Q4rf3HxhPEpAQHGMEPZmqAZvShGk0YceF",
	"04MUHCSO0XiPlpDCbdheWGB/yD5YsOzkw6/HTCt2JlRxi3pFrUUq+MBmosVjMTvRBt6c4diMJ+8uhn5R",
	"ZwrARV9rkwAtp9WQfUSqLLiQjDtmCuVEBggc3wtL9KqJ5QGRBduCtFiwvRMCKTf7Q/SY3oXVK3QQR3nD",
	"N9brzJsVqBo021O67ZGTxYYUgb0Lm449DRBQTThI2VrwJjG08eOkmBtuNiw3YNEXGk7VGSx5smGg1mzN",
	"DTt+e/n67B+zDxevZjjj5wNmHdLjRptry+aF83wXwhLHrymqgATSAK/FPYENOvxyDZDPuBRraLPNuMMz",
	"/6VvvO/iNMNZpQCgQKAtUSyDDPmfLzColNw6JCbb8zIwQHXAnZhLQLK98ZO5AaIXBuaJt1kqAPRgvGyV",
	"ZNcLJhRPnFgLtxlO1QcL7Dddv/dqfcKm0bNsGrG9ZywTqnBg92M2jQ5W+OyArXRh6MEYfytA0fbLxgz4",
	"EpHXHOUTEf2IrGCB3Do/QxumM+EcpHFJA9xGQJsAyA1yLLkxRU5qo7kKGmXpD3sOK74W2uxvn9ezrO+0",
	"pF5+q4qVernc0rBBpVIIqRWZfeVmZTjc9t8fEU5WIJhQCzDk2VexNZdS30A6nKrjNKUsA5f1W1J7c2Cf",
	"CyggZUWOVEa86MHMii/IyBee+mOKEgolBarmtKGD2rR72hvC8tuZp32wIN+6zXDSJfN3uN6KrJCOK9CF",
	"lZuScYh9CWHUDAbQL0pj8mQkoISgwCpX+mrefxO2wShn5x8YrAWlCPYfQwz2Dk0+LBaAcgJel9Vi7hWn",
	"GnwBo7cId7SLcH6Ls2z+OKIFiuwJxd78sh8yAIRv2FSwsr004nludCDTThJ5iSuJ9CiqVAGYYjxdC4sY",
	"+kUHwWEOeE9VYfkSWAo5JfOCdZQMudGSMKNH7SDLteFGILFvE4DUb2TNZYFM+5HUNEeNaUUKrMOAIbJX",
	"MFgaLpTPMDmj5TY7j18+33UwtZh8Kzs3k18ExfPJDp3QYN761ILY4rtFIWXMFNzUcPHUkN2ejY/YhffM",
	"2QdV21TKzp6DM5vBMWn6FfAUzO6z9Is9wOe78J8W4/ERsPEWbQ/Gu/NdM+sMd7Asg5NKfb3fSh0XGcZA",
	"pPejOJL8yyaKo7kuVAppI/6ptXj7bN6DGXgGC1aHhYU3lHkyIgU7ZG94bhvpMDo3twJhOrNq44r+Ueme",
	"ZjwnKcRjCySs1/G5N91UE+QMni4aT34O9rI8gEnbVrI97xlXZi9u2bz9Djx/JOMJQ4ptQdGKpZBxlcZh",
	"evAGRCphHx04YsEyP7jCYL3cy9SfxDRqbt3vhvRL6V3U5nmPW5Zz41AscgM1tjS+bbhjBmtQ2zo1bIXt",
	"5UKpplUgXEnzkB20LBO35PcT5SicwM03QwlglmfAct1RBF+j+RIGlBQagBqsD4bPoknFd8lKq+tNNPEM",
	"2JcFC3vrhtdnwrrKxNXsFca3SNXry12uwEKPKySyDFLBHciNp1gZVflSQsz4Wgs6dUoRDYK0MskdqKRi",
	"5ICRXelCou51yYq5lbaABOuJC9keDJdD9O869JpG3mV/rIFkey3mxDW2vY3fe04ljhIp8sFaOEprD3LE",
	"+egQlUGV/+lmbLdyPYEaMwx6dOEecs9LFU8xktPshgtHGpSXOpkSkxqxdhCHSgTuKqh/HI+T73Wrj8Z2",
	"GpEvnfn/vQutWcAyZg2n7LzUvt4+Uv4cZSGMbZiIp+w37uCGb9ilf7ftDh+Ne6NdA4Y/Lk9TjnxkVqAc",
	"/hdmBfyS/3RWoLnBDp3s0SwxGBg6waX95izNUR09NKBsZwHL9N2OlJ8D5d5z43oLt/61V8PItOhLi0yn",
	"XDayJXuUStWGiYwvqbSqFbxbUJ76vv1cwq1rInAX3z/+FMF/OD9rzfl0F0evEJWddQSh8qJnd6f4uNqh",
	"035DQ3ZR5Lk26IGtDECQMUuW6kKopQSfOfaHOGFX02gFUmqM/2U6ja5wYDvJ7IfaCbv6PQz2MhpmfGpP",
	"adLcsr2a4vsI4OuUDnEaodQjdA/K/4XPAvy7mLWG0tEgG/jxjZ8THBj+mkYpd3xCb0e5Wv4vVJPPn8bD",
	"4XAa3d0hpm0d29h6hK5vshKKQiiD4oosV7PCVl29Q0u2N+fJ9Q03KWvYsR6xuT+lH6i9E9qjNf3OZRpC",
	"sHVYLUGw+4+uK7SEYAuPT7vrC2/RIwkJ+Cpf6r0Fqij0JWebSqrPQnapYgqVcNeOZJwpoFOtDAMZCRxK",
	"1EK4gA7R6dYxCWrpVj0Fmy2dVRYsvOz2aa4g872Vs0o12Wjy++/j4fjg8CgejIfjp8+ex+Ph+KcXLz/F",
	"+Pzw6Ck9f/b8J3z+4uWnRrGqS51O4aq50E52qRXlmmyOZXtaARVxPaU8rVvcUv3xUFm16588sjblXTgK",
	"3VGxV0h+K4PsOLgGZXpPzxhfdN+iZ/m4jSuNZhlYy5fwIAoeSN+qpQHpMQb4hlE9yzDUgezD+WmnuWN3",
	"EayexPZ2qtB2Ca9/mPj7L+/Ob8b//dtSP6awvMuu95nKHZsuVViLC9jeuxzU8WkjogiWcL9DlcqWPKTm",
	"KvJXXFqH6TWQTw8W0/Ft3DujJoAPtZv6YavkXFbPunJbpULaHTOW7YVSRNUsNPV12Gm037aKZXXWx36D",
	"DEXVBUEi4yGFWhZcDg6+LfSoK0z3YF2fYZnPeoQp6I+WOs8G4sXgs/vWeKl0gO9BunayQxa4g1sJZrA+",
	"HGRH34JCX1Hc++NN37ymbR87ndPInS7mA/Z5a3f+RK56gqSrjvbd2naPfc6NznLXQ933BqerFAykjcYW",
	"uHWhyQwhDxn1hklBdQLLjJeYUuAZ3DrDEyfUcqowoPIARbNVZiFApnbkIMsld2DZHBbaAEu4lFVsWcZO",
	"nSj9VDmj08K32lGVoe1Dei34K+X2wyO2KFTKcW0uqf3mm/jxcwFm09fnyU2yYvSWdm5AwpqrBJhNtNm2",
	"jNtoMp7nUiQUl9tHW0mPS32G97HeLk32AO9lbTtfsWJvOJpoAz2cdN4iBTQcGI947HNj2qD/ya13a1r+",
	"zLe6MTvoFRDsI9N2MNnfA9Zr7DoW7Z4msu14sddj3rJtW91f95u1na1ifwdjhVa7GWFeCJlSWqqL+y/4",
	"jhI81vEsb7Hy4fjw6WB8MDh4dnkwnhyNJ+Px/+1tYRBulugs62vT+k0gafAdW3G7ape458nB4dHTXpB6",
	"tvbb6gGpq9aCckwT6lIfDA+fDcd9YHfCLBNFfQDXB8NxH7itY6qnNugRN4nf2lbfSW7ncUo/o87m/KeR",
	"/j+N9Lv5ZUfrQLd+4Mdttcig6qsS/r4AaDv8ImEN8s+2NJwREDqljQ/M/wy0CwLS20f8OERaCWiUlk7K",
	"uSTYGswcWWbDPB3iSpWnMC+WlJeg6Tfct+mXEWetTcKAjmp63C5bqDo8LMXlTnR14fLChfiMEbGH7Ek5",
	"zff0J1pqI774arbVEmL25A+rVej4d6ZIXIGO4v++ePc2Zk+kXi4y59/6iwCwWIiE3MRr2PxM5XSWc2Fs",
	"zJ4orfPy7oAE5YYNkjXQxwUj6pZZZCgCOK1NtsbgB0m3I/3dbV9NErB2dg2bWZ9eOv54wfwQ3Bg7/bWR",
	"Ar6GjXXoy9qNcvzW7xASA45Jra+LfMhecykto1Zdp9nxx4vZ8cnJq4uL2X+/+sfs9FcGai2MVuQpr7kR",
	"FO6Iqr7QrhpsdGEGHpnBNWwGote/KH3pHh171AzYq3pFKLw9sUdDnvEvWvEbO0x09oRpg0ddNuG+HI/H",
	"/hjfCHX6rp2v2J4cxVEm1JlP6E0O+txJotSspn8/8QNB6zP4swdw8erk/NVl4xz+iUPwizTOotdfBotG",
	"3t/m6G7uXR76qvwuaawXJi9WoVNlwxo1oG/aex/atMrAY9SDcmFhZq18MJn7ShGNLi7ORpdnF7T2xRHq",
	"DuVvRdmq4WDCcD6NOP54ETPq9AxdRQmXNSv1pHwf1OSPbETuyrxvb5shW9u+WwXCgQzl9TCW4VgqaY9O",
	"3/suICnUNUv1DTUZWCoLQpa7TUwlRYLtOyUDBHSLIHcsN2LNHTCEIxZsLnVyPQsPZyL3VyVMAfvDdiwc",
	"/gzSlaRq2H5y8PJwOB4eDr8xbVQSI+du9Vhi4FiWG1iIWyhboiRMRiMqq9oj/OvD+VmHKLRGkyhD9rox",
	"ubDA+NxqWTgIY4NyGn2wYOwo5Y6P9v0kvwpOmRfJNbiRx6eckW0G4XmR0wGNtunZhInqqjPh2+jYOccH",
	"pegXnNHq6apZgxmulhhLHxz+hJHHcDx6EbODcePvnw6HB8/p18FhzPD0D56/8L+fx+zg+cvh4bOn4fd+",
	"7y2YknnLboWZv53Txvyoe/EsdALguQuVirVICy4rUWAoaj7VgS51CbPZsjgm6yAy9AEOdrXJVdhZ8QVm",
	"842DNmIH46cvnv30fLyzbw7nIdeWgEKznu95ZR5gq62sglchN34g1hDKPX9aIuxzzqnIQNUBZkD2cPz0",
	"xS48aR67EalbjVYglivCLxe3lFb21cKq6dYAbqt94ccDv4+iXW2Kj8gN9XfpHE/IY0AVh5aXNG0U+6IG",
	"Xcixk9FoKdyqmKO+CQ55Oh85Hy10W+TKMMK3b4YeJCmuIaj+uu+Y7myZ6jphuFX65qxuOZ2qH35gH1ec",
	"spABMHVphTXCxVxbWpWzBnQKhGsMGi7Q8ftTqtz/+OOrKi3+G6jAvT/+OGGU1aHm0bqqu3dydvp+v5NJ",
	"94BoQnmzCyFcQMaVE0ldLyB8mtcmy7uiA2LY8m6Xh3deZuQQVp1pMzAIecdg+Ck96a/BBUxeF+iy47S3",
	"r85jlkhurViEJGRMm1qGva6hbJb13gXLJVcKUqTwr6VUU/czd0C9vRI46mrHSs7w7DAUepTqxI4qs1gd",
	"HVD+9oOFvuNLuGKmUBhkq5RLrYBuEtcdflwxz5IskYV1YOjczuiwa1JuHTrqKLh1YMjLen8amoNBJQKI",
	"SF2OuBrxXPi7Ole1h9zKB9LM6lTre4LlWZwf/8ZykYMUyq/SPLUy00+qM0OuhbQ8vc8Fl8JtcMoJKGe4",
	"pIgsnAzG4mrJeGK0tSwVaIjmhYOUKZ36hd6j9Ug2A7qd4oe3BIFqj6E1UgJfg2XoFuIIw6sgbz8c2Wvg",
	"+DOc4A+sT0Q8p/lqGnJak6v9hZrQblXeyLzqqTRdeSjH708JxOPOpJQOn+5EhyDjjnD4RSj0mquO15iC",
	"1nIXb2o5Dq50kGcP0Bc9q60SQHzNGt3ffxBP4MEPvOauNYHNeQIBEhXvm3hRCbeqBFu2d7WzFny1j/yP",
	"HpQHFsqtJxVRECBd4Wq3mIQgf+/qn+ruCX08V4EWKKsn3AJh7wnjOTVmxIQDT0YDzghYcxmztbDoCISe",
	"OeJlT/WWVtxmmte17qsEqSymVv1z++x/NrmrAYP9Gnhsg8COm1xnW0XOq+710MB6J/77DTj/cODvHrHL",
	"y7PySgTdiw1KNShnwrsVWrZv+6NjH6p5XMhKhipt/lj8mwK1uy7oof2tQJX0pbJdx+0bWsgtn/2Q+kKG",
	"WNQkbvAtTm8VCEnNhToU2wsFwRVXqUT/X4BMq1qgVvtUxZMigVCJKJ0KKdk5ujeWnYO/p93xMGo7ImHJ",
	"KT/ohPOX8euvfUSNLH60PuAyX/ED+liEDwSjSXQ0HA+Pojiqwhp/JZaCQW37siO5FOiF4057LvKzwvrr",
	"ykHxt432VjNA6bG8CczqT58YvRKDHh73XYSdz2vQxwVc5TqEL1vg4A9lB/fPVbMBPn7NrfdaUvApM2Gd",
	"SEo0iKfeVGLUdVCqiwWlcmkK9IC9uU+/75Cxb5YVFmQSf517t4biRpLF5g0u1MiH5YXBIU0DStVVfRhz",
	"7VblhUskimtU6sqDeuVdafx1dXX1h0XT9nWqWKt5csfXIEhtxn6wX8YrVsUYPqKteQDhiOLyVetzHzjk",
	"2XhcvWx/98S/rV5WXxrxgKdThf8ifH03VXe0C5LCKhY7TctPDlz6CkOIO3/R6aaMAcBnDRvF6hElZasP",
	"OT3qEwhlH8Rdu76BETA98CabZPJwPP5Xrx3qn7R4X4WW+DNltqDc3aKQkqL3p/9CTHz7Wg8Gp2rNpUjL",
	"kB/XffbXrBuc4BBoQRgYR7bIMm42JWv0aD8Ly4y+5oXDvRe2W4cGzxBsaGZseM0hW9DsqvYaVW458bb8",
	"lFPlftN96cod9OETeYlPbNs5DO6PT5/eutg3pWAIoFLLRKiJdnvXGsFdGQEhjIbj11XoW1ehH+fpNm7l",
	"hAsbGFX5PfhhjajDaUZ5t/r2XQOXMtYc0KcisuBMlcmvTmvW/oQdJ5R9bHZBBy+k3v02HPKM21ORoiEl",
	"sRa8dmcDgVpur79H1eiTJ3IFEkP6Xbvm+2497e6kf1TzvPePv0/rfE9L5f6ftISNG95UP0iad7gRQgpp",
	"4XUNhvrBv6HjWEjKQvnrZGsEYSAtVMqVoy8ZlOKwHX/h46pCQVKFvkzVFbPJA9cEhvKXR4kNrppqTycO",
	"3MA6Azy7qiI6C0ZgTOwL1WV8F7NMW8eq+uN+Bxoq0asJRYFlA1vQIo0PlZGiaIT4Ta/A8zFyXbMDtsNd",
	"k67v0LD9Pbfags9AShEH/b7F9shP251k0+hTbd+n6k3vjZsuK92PW++9tz78yPt4UE44y1faacrbsIQ7",
	"FJqeqX9OckIrdBAgBP/pHsenNEx1ZP+dPKDWZaO/2ANqX3rAtXcJVRvmVlWCpG1QShuk3SsKzU8xzWl4",
	"T29LxwupaV8mHv+N/LCn46fff91wMVaje1Go9N/K/yslpKEFvctXf3hjCa6v+9MVRllyVSyJfLfXPG58",
	"IdK3Cbf7uasorOyy9h5ON/mxK3v4tyqvQfV75Sxb8TWwK9+SfsVssViI29Kghh5vv8rxrrZ9tld+gYts",
	"yntZWMbVpget3qA3GMjQQ75rR7vSOa+y3G18E0I5oWzU8nn5hv/ZcD3RvwyfbWh+xyYpPwLRUYxnwro3",
	"ZVP9d9NMW/ctdomGLZOJPYrh30ZQzvp8ci8q/jB3h0fnvmrjP/m0I7lWJV/qDnOnGQ+t595JIzbaJUQn",
	"Pjl3XrbqCymcCD5M3cyfFdZNpupgyF75vF25Xtmx7/mzzHHYqTocsnPCmISg6uefqqMhuwCV9uypvGzJ",
	"LbsK+7uqvq2QghVLf4XfNr8x4ECC9V9sCZ9f8ChTgTwprNOZ+AKNqwZSL0XSDdDqRNXOEG2X8FUubCdf",
	"unflvzJSvRhqpW59xrydb80N0OeFP3dVUzvp+lD+acuHbF/5qJw0Yg8/6t7LB9WEcB4Nv27auW3xJkA6",
	"C5Am/ns8y0Kk6NWvwdg6+YUA6CJGOZq9blzEmLC3UBgumQLnv4XGDdDkLddtql5rU/FdyIDWvE5++3bC",
	"Oa4+kuJZZWBFClN1JcV8VE29YjlPrqnSTh91LrPXNSM9fDOlrTu9cn8fbmd8H3+yfbXoL3Yoty6X9CjM",
	"sPnyywv/8ef+f5opXP3o+69eFbEqV6NQ7a8udhyW/S0b6kHUNm9TWztvSRt3NO71OreubMRsWV01iekD",
	"qv5ai3c7u3dGhj2Bovt7dYfjuwnW9m2dHiqHIc2LGx2P3ZX72BpFzafIGbbn0wqNMlrgn6oIN+K5iO4+",
	"3f2/AAAA//9gbAxzxmEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
